export const SET_AUTH_USER = "SET_AUTH_USER";
export const RECEIVE_USERS = "RECEIVE_USERS";
export const RECEIVE_QUESTIONS = "RECEIVE_QUESTIONS";
export const SET_ANSWER_TO_QUESTION = "SET_ANSWER_TO_QUESTION";
export const SAVE_QUESTION = "SAVE_QUESTION";
export const CREATE_USER = "CREATE_USER";
